# Generated by Django 5.2.15 on 2026-07-08 11:10

import catalogo.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='slug')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Gerado automaticamente se deixado em branco.', max_length=20, unique=True, verbose_name='código (SKU)')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', validators=[catalogo.validators.validar_tipo_imagem, catalogo.validators.validar_tamanho_imagem], verbose_name='imagem')),
                ('unidade_medida', models.CharField(choices=[('unidade', 'Unidade'), ('kg', 'Quilo'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro')], default='unidade', max_length=10, verbose_name='unidade de medida')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preço de venda')),
                ('preco_custo', models.DecimalField(blank=True, decimal_places=2, help_text='Uso interno da administração. Nunca é exposto ao aluno.', max_digits=7, null=True, verbose_name='preço de custo')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='estoque')),
                ('estoque_minimo', models.PositiveIntegerField(default=0, help_text='Usado para alertar necessidade de reposição.', verbose_name='estoque mínimo')),
                ('destaque', models.BooleanField(default=False, verbose_name='destaque no cardápio')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['categoria__ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='preço promocional')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(verbose_name='data de fim')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='catalogo.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
