# Generated by Django 5.2.15 on 2026-08-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_admininvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_sub',
            field=models.CharField(blank=True, help_text='Identificador permanente da conta Google utilizado no login social.', max_length=255, null=True, unique=True, verbose_name='ID da conta Google'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Endereço de e-mail do usuário.', max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica se este usuário pode acessar o sistema.', verbose_name='Usuário está ativo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indica se este usuário pode acessar o Django Admin.', verbose_name='Usuário é da equipe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Nome completo do usuário.', max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
