# Generated by Django 5.2.15 on 2026-08-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status_atualizado_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Marca desde quando o pedido está no status atual. Usado no cancelamento automático e nos relatórios.', verbose_name='status atualizado em'),
        ),
    ]
